service: cv-exercise-api

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs12.x
  environment:
    DYNAMODB_JOBS_TABLE: cv-exercise-resources-${opt:stage, self:provider.stage}-jobs
    SQS_QUEUE_JOBS: cv-exercise-resources-${opt:stage, self:provider.stage}-jobs
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
      Resource: arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_JOBS_TABLE}
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource: arn:aws:sqs:eu-west-2:041087672119:cv-exercise-resources-dev-jobs # hack https://github.com/aws/serverless-application-model/issues/1699

functions:
  create:
    handler: handler.create
    events:
      - http:
          method: post
          path: job
  get:
    handler: handler.get
    events:
      - http:
          method: get
          path: job/{id}
  
