service: cv-exercise-resources

provider:
  name: aws
  region: eu-west-2
  environment:
    DYNAMODB_JOBS_TABLE: ${self:service}-${opt:stage, self:provider.stage}-jobs
    SQS_QUEUE_JOBS: ${self:service}-${opt:stage, self:provider.stage}-jobs

resources:
  Resources:
    TasksDynamoTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_JOBS_TABLE}
    TaskQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:provider.environment.SQS_QUEUE_JOBS}
        