service: cv-exercise-api

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  region: eu-west-2
  environment:
    DYNAMODB_JOBS_TABLE: cv-exercise-resources-${opt:stage, self:provider.stage}-jobs
    SQS_QUEUE_JOBS: cv-exercise-resources-${opt:stage, self:provider.stage}-jobs
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
      Resource: arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_JOBS_TABLE}
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource: arn:aws:sqs:${opt:region, self:provider.region}:*:{self:provider.environment.SQS_QUEUE_JOBS}

functions:
  task:
    runtime: nodejs12.x
    events:
      - http:
          method: post
          path: task
    handler: handler.create
