service: cv-exercise-api

provider:
  name: aws
  region: eu-west-2

plugins:
  - serverless-plugin-typescript

functions:
  time:
    runtime: nodejs12.x
    events:
      - http:
          method: get
          path: time
    handler: handler.testHandler