service: cv-exercise-web

provider:
  name: aws
  region: eu-west-2

functions:
  hello:
    runtime: python3.6
    events:
      - http:
          method: get
          path: greet
    handler: handler.hello